### ISSUE TITLE
Cannot Locate Rosdep Definition, ROS Humble, Ubuntu Jammy

### ISSUE THREAD

**Issue by BashByr** [turtlebot/turtlebot4_desktop#5]
**Please provide the following information:**
 - OS: Ubuntu 22.04.2 LTS
 - ROS Distro: Humble
 - Built from source or installed: Source
 - Package version: commit hash: 9d13b20

 **Expected behaviour**
Successful source installation of turtlebot4_desktop using rosdep in ROS Humble.

 **Actual behaviour**
`ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
turtlebot4_viz: Cannot locate rosdep definition for [turtlebot4_description]`

**To Reproduce**
Provide the steps to reproduce:
1. `cd ~/turtlebot4_ws/src`
2. `git clone --branch humble https://github.com/turtlebot/turtlebot4_desktop.git`
3. `cd ~/turtlebot4_ws`
4. `rosdep update`
5. `rosdep install --from-path src -yi --rosdistro=humble`

**Other notes**
I have just begun the process of moving my physical TurtleBot4 from galactic to humble. Before installing ros humble and turtlebot4_robot on the on-board raspberry pi, I first started by making sure turtlebot4_desktop can run on my laptop.

Side question: before moving the raspberry pi to ROS humble, I would need to update its ubuntu version from focal to jammy, correct? This is what I did to run humble on my laptop.

**Comment by roni-kreinin** [comment]
@BashByr I bloomed the `turtlebot4` package on Friday for Humble and the PR was merged this morning. I expect the binaries to be available by the end of the day. Once available, you will want to modify your `/etc/apt/sources.list.d/ros2-latest.list` file to use the `http://packages.ros.org/ros2-testing/ubuntu` package server, then call `sudo apt update`. You should now be able to run `rosdep install` and get the packages.

In the meantime, you can simply clone the [turtlebot4](https://github.com/turtlebot/turtlebot4/tree/humble) repo to your workspace and build it.

As for the physical robot, I will be releasing the `turtlebot4_robot` package this week as well, and working on creating a new RPI4 image. It will run Ubuntu 22.04. I would recommend you wait for that image rather than trying to set it up on your own.

**Comment by BashByr** [comment]
Perfect, thanks a ton for your time. I will try the installation later today or tomorrow if it still isn’t available. Closing this issue for now.
